# Generated by Django 5.1.5 on 2025-02-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_alter_product_price_per_sq_m_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Розмір товару (наприклад, 70x190)', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна для цього розміру', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='main.product')),
            ],
            options={
                'ordering': ['product', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
