# Generated by Django 5.1.5 on 2025-02-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_price_per_sq_m_alter_product_slug'),
        ('size', '0002_alter_size_options_alter_size_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='main.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='size.size')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
