# Generated by Django 5.1.5 on 2025-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ratings_photos/'),
        ),
    ]
