# Generated by Django 5.1.5 on 2025-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_popular'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'slug'], name='main_catego_id_ddca48_idx'),
        ),
    ]
