# Generated by Django 5.1.5 on 2025-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='novelties',
            field=models.BooleanField(default=False),
        ),
    ]
