# Generated by Django 5.1.5 on 2025-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_best_product_novelties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_sq_m',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ціна за 1 кв.м', max_digits=10),
        ),
    ]
