# Generated by Django 5.1.5 on 2025-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_price_per_sq_m_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_sq_m',
            field=models.DecimalField(decimal_places=2, help_text='Ціна за 1 м²', max_digits=10),
        ),
    ]
