# Generated by Django 5.1.5 on 2025-02-23 20:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
