# Generated by Django 5.1.5 on 2025-02-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('size', '0005_alter_productsize_price_alter_productsize_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='size.size'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
