# Generated by Django 5.1.5 on 2025-02-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('processing', 'В обробці'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='pending', max_length=20),
        ),
    ]
